#!/usr/bin/env ansible-playbook

- name: 'install nextcloud'
  hosts: nextcloud
  become: true

  roles:
    - prep_apache
    - prep_os
    - prep_redis
    - prep_php
    - prep_mariadb
    - { role: prep_letsencrypt,    when: ssl_certificate_type  == 'letsencrypt' }
    - { role: prep_selfssl,        when: ssl_certificate_type  == 'selfsigned' }
    - prep_nextcloud
    - nc_fail2ban

  post_tasks:
    - name: We are ready
      debug:
        msg: 
          - "Your Nextcloud at https://{{ fqdn }} is ready."
          - "Login with user: {{ nc_admin }} and password: {{ nc_passwd }} "
          - "Other secrets you'll find in the directory {{ credential_store }} "
 
