---
# tasks file for prep_httpd

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install needed packages
  yum:
    name:
      - httpd
      - firewalld
      - mod_ssl
    state: latest

- name: open firewall ports 22/{{ nc_web_port }}/{{ nc_ssl_port }}
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: false
    state: enabled
  with_items:
    - 22/tcp
    - '{{ nc_web_port }}/tcp'
    - '{{ nc_ssl_port }}/tcp'
   
- name: set apache
  include_tasks: set_apache.yml

- name: set default_htaccess
  include_tasks: set_htaccess.yml
  
  
- name: set apache vhosts
  include_tasks: set_apache-vhosts.yml

- name: stop and enable httpd
  systemd:
    name:    httpd
    state:   stopped
    enabled: true

- name: create some folders
  file:
    name: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{ nc_datadir }}',        owner: '{{ web_user }}', group: '{{ web_group }}', mode: '0750' }
    - { path: '/var/www',                owner: '{{ web_user }}', group: '{{ web_group }}', mode: '0750' }
    - { path: '/upload_tmp',             owner: '{{ web_user }}', group: '{{ web_group }}', mode: '0755' }

- name: install pip netaddress
  pip:
    name: netaddr
    state: latest
  when: false
  
- name: set netmask
  set_fact: 
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: use ansible_fqdn if fqdn is not defined
  set_fact:
    fqdn: "{{ fqdn if ( fqdn ) else ansible_fqdn }}"

- name: Change Directory Permission -  Apache Log
  file: 
    path: "/var/log/httpd/" 
    state: directory
    recurse: yes 
    mode: 0755
