---
# tasks file for prep_mariadb


- name: add MariaDB repo
  yum_repository:
    name: mariadb
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    enabled: 1

- name: install MariaDB
  yum: 
    name:
      - MariaDB-server
      - MariaDB-client
    enablerepo: mariadb 
    state: latest
  register: install_mariadb

- name: install MySQLdb python package for database setup
  yum: 
    name: MySQL-python 
    state: present
  when: false

- name: enable MariaDB
  systemd:
    name: mysql
    enabled: true

- name: stop if installed
  systemd:
    name: mysql
    state: stopped
  when: install_mariadb is changed

- name: install PyMySQL
  pip: 
    name: PyMySQL
    state: latest
  become: true

- name: create conf dir
  file:
    name: "{{ mariadb_conf_dir | dirname }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure mariadb
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_conf_dir }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb

- name: start and enable MariaDB
  systemd:
    name: mysql
    state: restarted

- name: remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: "{{ mariadb_sock_dir }}/mysqld.sock"

- name: remove test db
  mysql_db:
    name: test
    state: absent
    login_unix_socket: "{{ mariadb_sock_dir }}/mysqld.sock"
  
- name: create nextcloud db
  mysql_db:
    name: "{{ nc_db }}"
    collation: utf8mb4_general_ci
    encoding: utf8mb4
    login_unix_socket: "{{ mariadb_sock_dir }}/mysqld.sock"

- name: create nextcloud user
  mysql_user:
    name:     "{{ nc_db_user }}"
    password: "{{ nc_db_passwd }}"
    priv:     "{{ nc_db }}.*:ALL"
    state: present
    login_unix_socket: "{{ mariadb_sock_dir }}/mysqld.sock"
